'use strict';

(function () {
  // mithril required
  // store.js required
  // uiComponents.js required

  // see https://mithril.js.org/#components
  // see https://mithril.js.org/components#passing-data-to-components
  //window.data = {};
  //data.count = 0;

  //storeSet 'count1', 0
  //storeSet 'count2', 0

  //elById = document.getElementById.bind(document)
  var Counter;

  Counter = {
    oninit: function oninit(vnode) {
      var attrs;
      this.domElementId = vnode.attrs.domElementId;
      attrs = storeGet('ui.' + this.domElementId);
      if (attrs.delta == null) {
        attrs.delta = 1;
      }
      if (attrs.defaultCounterValue == null) {
        attrs.defaultCounterValue = 7;
      }
      return storeSet('ui.' + this.domElementId, attrs);
    },
    view: function view(vnode) {
      var attrs, count, counterPath, delta, deltaCaption, self;
      attrs = storeGet('ui.' + this.domElementId);
      counterPath = attrs.counterPath;
      delta = attrs.delta || 1;
      //console.log(JSON.stringify(vnode.attrs) + ' rerender')
      self = this;
      //m("main", [
      //m("h1", {class: "title"}, "My first app"),
      // changed the next line

      //m 'button', { onclick: ->
      //count = storeGet(self.count_path)
      //storeSet self.count_path, count + self.delta
      //return
      //}, self.count_path + ': ' + storeGet(self.count_path)
      deltaCaption = delta === 1 ? '' : '(Δ=' + delta + ') ';
      count = storeGet(counterPath);
      if (count == null) {
        storeSet(counterPath, attrs.defaultCounterValue);
      }
      return m(
        'button',
        { onclick: function onclick() {
            count = storeGet(counterPath);
            return storeSet(counterPath, count + delta);
          } },
        counterPath + ': ' + deltaCaption + storeGet(counterPath)
      );
    }
  };

  //,
  //)
  window.uiComponents.types.counter = Counter;

  //m.mount elById('counter1'), view: ->
  //m Hello,
  //count_path: 'count1'

  //m.mount elById('counter1_10'), view: ->
  //m Hello,
  //count_path: 'count1',
  //delta: 10

  //m.mount elById('counter2'), view: ->
  //m Hello,
  //count_path: 'count2'

  //return

  // ---
  // generated by js2coffee 2.2.0
}).call(undefined);